preset           = "strict"
project-excludes = [".venv/**", "template/**", "assets/**"]
project-includes = ["**/*.ipynb", "**/*.py*"]
python-version   = "{{ min_python_version }}"
search-path      = ["src", "."]
